### ISSUE TITLE
android-X.jar

### ISSUE THREAD

**Issue by A-AFTAHI** [reddr/LibScout#11]
I was trying around different versions of android.jar and i can't figure out the difference when using LibScout.
so i wonder **how does the android.jar version used either on profiling or matching affect the result**?
**what would happend if i create a profile with a given version and try to match it using an other android-X.jar version?**

**Comment by reddr** [comment]
The Android SDK needs to be provided in order to be able to distinguish App/Library Code from Framework Code (Code here includes Types/Invocations etc). As long as a reasonable new version is used (e.g. API 23+), there should be no difference, as most libraries are pretty conservative in there min. required SDK.  
However, if you would use, say API 16 and the lib would use classes available in 19+, then there could be some misclassification that might effect precision.
